name: methods3_2024
channels:
- defaults
- conda-forge
dependencies:
## Python version
- python>=3.10

## Python packages
- pip
- scikit-learn
- matplotlib
- numpy
- scipy
- pandas
- seaborn

## R Version
- r-base=4.2.1

## R packages
- r-lme4
- r-multcomp
- r-reticulate
