---
title: "assignment_2_part_1, Methods 3, 2024"
date: "2024-09-19"
output: html_document
---
REMEMBER: In your portfolio, make sure to include code that can reproduce the answers requested in the exercises below (__MAKE A KNITTED VERSION__). If it does not KNIT, it cannot be part of your portfolio

# Exercises and objectives
The objectives of the exercises of this assignment are:  
A) Download and organise the data and model  
B) Fit multilevel models for response times  
C) Fit multilevel models for binomial data  
D) Fit multilevel models for count data  

## Exercise A - Download and organise the data and model

Go to https://osf.io/ecxsj/files/ and download the files associated with Experiment 2 (there should be 29).  
The data is associated with Experiment 2 of the article at the following DOI https://doi.org/10.1016/j.concog.2019.03.007  

1) Put the data from all subjects into a single data frame  
2) Describe the data and construct extra variables from the existing variables  
    i. add a variable to the data frame and call it _correct_ (have it be a _logical_ variable). Assign a 1 to each row where the subject indicated the correct answer and a 0 to each row where the subject indicated the incorrect answer (__Hint:__ the variable _obj.resp_ indicates whether the subject answered "even", _e_ or "odd", _o_, and the variable _target_type_ indicates what was actually presented.
    ii. describe what the following variables in the data frame contain, _trial.type_, _pas_, _trial_, _target.contrast_, _cue_, _task_, _target_type_, _rt.subj_, _rt.obj_, _obj.resp_, _subject_ and _correct_. (That means you can ignore the rest of the variables in your description). For each of them, indicate and argue for what `class` they should be classified into, e.g. _factor_, _numeric_ etc., and apply that class! 

## Exercise B - Fit multilevel models for response times  
We __only__ look at the _experiment_ trials (_trial.type_)  

1) Choose the first four subjects and plot their Quantile-Quantile (Q-Q) plots for the residuals of their objective response times (_rt.obj_) based on four models (one for each subject) where only (first-level) intercept is modelled  (use _qqnorm_ and _qqline_)
    i. comment on these    
    ii. does a log-transformation of the response time data improve the Q-Q-plots?
2) Do a partial pooling model modelling objective response times (log-transformed) as dependent on _task_ ($X$-matrix), including all subjects  
    i. which intercepts (ignore slopes for now) would you include among your second-level effects ($Z$-matrix) and why? Choose from the variables: _pas_, _cue_, _target_type_, _subject_ and _correct_
    ii. explain in your own words what your chosen model says about response times between the different tasks  
    iii. now make a model that has second-level intercepts for _obj.resp_ and _target_type_: explain why the fit is singular (Hint: read the first paragraph under details in the help for `isSingular`)
    iv. in your own words - how could you explain why your model would result in a singular fit? (Draw on the background knowledge from the design of the task)

## Exercise C - Fit multilevel models for binomial data
We __only__ look at the _experiment_ trials (_trial.type_)  

1) Fit a multilevel model that models _correct_ as dependent on _task_ with a unique intercept for each _subject_  
    i. does _task_ explain performance?  
    ii. add _pas_ as a main effect on top of _task_ - what are the consequences of that?  
    iii. now fit a multilevel model that models _correct_ as dependent on _pas_ with a unique intercept for each _subject_
    iv. finally, fit a model that models the interaction between _task_ and _pas_  and their main effect, still with a unique intercept for each _subject_  
    v. describe in your own words which model is the best in explaining the variance in accuracy, and based on your chosen model - write a short summary on what this says about accuracy as dependent on _pas_ and _task_. You may include informative plots 
 
## Exercise D - Fit multilevel models for count data  
We __only__ look at the _experiment_ trials (_trial.type_)  

1) Initialise a new data frame, `data.count`. _count_ should indicate the number of times they categorized their experience as _pas_ 1-4 for each _task_. I.e. the data frame would have for subject 1: for task:singles, pas1 was used # times, pas2 was used # times, pas3 was used # times and pas4 was used # times. You would then do the same for task:pairs and task:quadruplet  

```{r}
## you can start from this if you want to, but you can also make your own from scratch
data.count <- data.frame(count = numeric(), 
                         pas = numeric(), ## remember to make this into a factor afterwards
                         task = numeric(), ## and this too
                         subject = numeric()) ## and this too
```
2) Now fit a multilevel model that models a unique "slope" for _pas_ for each _subject_, $Z$, with the interaction between _pas_ and _task_ and their main effects being modelled on the first level, $X$
    i. which family should be used?  
    ii. why is a slope for _pas_ not really being modelled, and what are we modelling instead?  
    iii. if you get a convergence error, try another algorithm (the default is the _Nelder_Mead_) - try (_bobyqa_) for which the `dfoptim` package is needed. In `glmer`, you can add the following for the `control` argument: `glmerControl(optimizer="bobyqa")` (if you are interested, also have a look at the function `allFit`)
    iv. when you have a converging fit - fit a model with only the main effects of _pas_ and _task_. Compare this with the model that also includes the interaction 
    v. indicate which of the two models, you would choose and why  
    vi. Make a plot with four subplots that shows the estimated amount of ratings, $\hat y$ for four subjects of your choice as compared to the measured count, $y$. Also include the first-level, $X$, response for _pas_ (aggregating over _task_).
    vii. based on your chosen model and the plot - write a short summary on what this says about the distribution of ratings as dependent on _pas_ and _task_ and their interaction (you can create plots for all subjects to inform your summary, but only include four subplots in your summary)


